const STORE='viva-data-v1';
document.documentElement.classList.toggle('native-app',!!window.ViveNative);
const DEFAULT_UPDATE_URL='https://nandydem2-afk.github.io/viveplus-updates/release.json';
if(!localStorage.getItem('vive-update-url'))localStorage.setItem('vive-update-url',DEFAULT_UPDATE_URL);
const MENU_UPDATE_VERSION=6;
const MENU_UPDATE_MEALS=[
  {id:'menu6-desayuno',type:'Desayuno',name:'Avena con yogur y fresas',amount:'40 g copos de avena Brüggen\n120 ml bebida de arroz y avellana\n10 g chía\n125 g yogur sin lactosa\n80 g fresas',icon:'🥣',tone:'yellow',notes:'Avena, chía y bebida en remojo la noche anterior. Café opcional; cantidad no indicada.'},
  {id:'menu6-comida',type:'Comida',name:'Bowl de salmón y arroz',amount:'160 g salmón\n60 g arroz basmati en seco\n30 g rúcula\n70–80 g tomate\n50 g pepino\n10–15 ml salsa de soja Kikkoman clásica',icon:'🍣',tone:'mint',notes:'Limón opcional; cantidad no indicada. Sin aceite añadido en esta comida.'},
  {id:'menu6-merienda',type:'Merienda',name:'Fruta si hay hambre',amount:'1 ud mandarina o kiwi',icon:'🍊',tone:'peach',optional:true,notes:'Solo si hay hambre. Elegir una de las dos frutas.'},
  {id:'menu6-cena',type:'Cena',name:'Tortilla con patata y espinacas',amount:'3 ud huevos pequeños\n150–180 g patata\n80–100 g espinacas\n20 g queso curado\n5 g AOVE',icon:'🍳',tone:'lavender',notes:'Patata en airfryer. Tortilla o revuelto con huevos, espinacas y queso.'}
];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const uid=()=>Math.random().toString(36).slice(2,10);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fmtDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString('es-ES',{day:'numeric',month:'long'});
const starter=()=>({schema:'viva.health.v1',updatedAt:new Date().toISOString(),profile:{name:'',height:null,weight:null,waist:null,goal:'',sleep:null,activity:'',limitations:'',dietNotes:'',notes:''},meals:[],workouts:[{id:'wA',name:'Sesión A',subtitle:'Tu rutina',day:'',exercises:[]},{id:'wB',name:'Sesión B',subtitle:'Tu rutina',day:'',exercises:[]},{id:'wC',name:'Sesión C',subtitle:'Tu rutina',day:'',exercises:[]}],logs:[],metrics:[],wearableDays:{},wearableWorkouts:{},mealChecks:{},mealNotes:{},workoutNotes:{},aiNotes:[]});
const homeWorkouts=()=>{
  const exercise=(id,name,icon,reps,count,note)=>({id,name,icon,sets:Array.from({length:count},()=>({kg:0,reps})),note});
  return [
    {id:'homeA',name:'Casa A',subtitle:'Fuerza en casa · objetivo 40 min',day:'3 días por semana · lunes, miércoles y viernes',exercises:[
      exercise('homeA-press','Press de pecho con mancuernas en banco','💪',8,3,'8–12 repeticiones · banco plano a 180°, palmas enfrentadas y muñeca recta. Primera semana: 2 series.'),
      exercise('homeA-row','Remo con mancuerna y apoyo','↗',10,3,'10–12 por lado · apoya el antebrazo libre en el banco si la muñeca derecha molesta al apoyar la mano; muñeca que levanta recta.'),
      exercise('homeA-chair','Sentadilla a banco','🦵',8,2,'8–12 repeticiones · toca el banco con control y vuelve a subir. Empieza sin peso; añade mancuernas a los lados solo si pie, cadera y muñeca lo toleran.'),
      exercise('homeA-bridge','Puente de glúteos en el suelo','◒',8,2,'8–12 repeticiones · sin peso al empezar, pies al ancho de caderas. Reduce si aumenta el dolor lateral de cadera o del pie.'),
      exercise('homeA-hip','Empuje lateral de rodillas sentado','◒',4,2,'4 repeticiones de 10–20 segundos · banda o cinturón alrededor de los muslos; empuja suave sin dolor lateral creciente.'),
      exercise('homeA-lateral','Elevaciones laterales sentado','🏋️',12,2,'12–15 repeticiones · mancuernas ligeras, muñecas rectas y sin impulso.'),
      exercise('homeA-deadbug','Dead bug','◎',8,2,'6–10 por lado · alterna brazo y pierna contrarios sin arquear la espalda.')
    ]},
    {id:'homeB',name:'Casa B',subtitle:'Fuerza en casa · objetivo 40 min',day:'3 días por semana · lunes, miércoles y viernes',exercises:[
      exercise('homeB-shoulder','Press de hombros en banco','💪',8,3,'8–12 repeticiones · respaldo a 90° y mancuernas con agarre neutro. Primera semana: 2 series.'),
      exercise('homeB-pullup','Dominadas asistidas con banda','↙',5,3,'5–8 repeticiones · banda y barra bien fijadas, control al bajar y muñecas alineadas. Si reaparece dolor, chasquido o síntomas en los dedos, cambia por jalón con banda.'),
      exercise('homeB-chair','Sentadilla a banco','🦵',8,2,'8–12 repeticiones · toca el banco con control y vuelve a subir. Empieza sin peso; añade mancuernas a los lados solo si pie, cadera y muñeca lo toleran.'),
      exercise('homeB-hinge','Peso muerto rumano con mancuernas','◒',8,2,'8–10 repeticiones · mancuernas ligeras a los lados, rodillas suaves y cadera hacia atrás; baja solo hasta donde mantengas espalda y muñecas rectas.'),
      exercise('homeB-press','Press inclinado con mancuernas','💪',8,2,'8–12 repeticiones · respaldo a 30–45°, agarre neutro y muñecas rectas. Prioriza movimiento controlado y sin dolor.'),
      exercise('homeB-hip','Empuje lateral de rodillas sentado','◒',4,2,'4 repeticiones de 10–20 segundos · banda o cinturón alrededor de los muslos; empuja suave sin dolor lateral creciente.'),
      exercise('homeB-deadbug','Dead bug','◎',8,2,'6–10 por lado · alterna brazo y pierna contrarios sin arquear la espalda.')
    ]}
  ];
};
const HOME_EXERCISE_DETAILS={
  'homeA-press':{photo:0,guide:'Pon el banco plano (180°) y túmbate con la espalda apoyada. Sujeta las mancuernas con las palmas enfrentadas; baja los codos de forma controlada hasta una posición cómoda y empuja hacia arriba sin doblar las muñecas.'},
  'homeA-row':{photo:1,guide:'Apoya la mano o el antebrazo libre y la rodilla del mismo lado en el banco. Con la espalda estable y la muñeca que levanta recta, lleva la mancuerna hacia la cadera y bájala despacio. Cambia de lado.'},
  'homeB-pullup':{photo:null,guide:'Fija la banda a la barra y coloca un pie en ella con cuidado. Desde un agarre cómodo y muñecas alineadas, sube ayudándote con la banda y baja en 2–3 segundos sin dejarte caer. Si la muñeca protesta, haz un jalón con la banda anclada a la barra en su lugar.'},
  'homeA-chair':{photo:6,guide:'Ponte delante de un banco firme. Flexiona cadera y rodillas hasta tocar el banco suavemente, sin desplomarte, y vuelve a subir. Ajusta la altura o recorrido si molestan el pie o la cadera.'},
  'homeA-bridge':{photo:2,guide:'Túmbate boca arriba, dobla las rodillas y deja los pies apoyados. Eleva la cadera apretando los glúteos, sin arquear la espalda, y baja despacio.'},
  'homeA-lateral':{photo:3,guide:'Siéntate erguido con una mancuerna ligera en cada mano. Eleva los brazos hacia los lados hasta la altura de los hombros, con codos ligeramente flexionados, y baja despacio.'},
  'homeA-deadbug':{photo:4,guide:'Túmbate boca arriba con brazos hacia el techo y rodillas sobre las caderas. Extiende a la vez un brazo y la pierna contraria sin despegar la zona lumbar del suelo; vuelve y cambia de lado.'},
  'homeA-hip':{photo:null,guide:'Siéntate en una silla firme con pies apoyados y rodillas al ancho de caderas. Coloca un cinturón o banda firme alrededor de los muslos, justo encima de las rodillas. Empuja ambas rodillas hacia fuera de forma gradual sin separarlas; mantén la tensión y relaja despacio.'},
  'homeB-shoulder':{photo:5,guide:'Pon el respaldo del banco vertical (90°). Siéntate con la espalda apoyada y las mancuernas a la altura de los hombros, palmas enfrentadas. Empuja hacia arriba sin doblar las muñecas y baja de forma controlada.'},
  'homeB-chair':{photo:6,guide:'Ponte delante de un banco firme. Flexiona cadera y rodillas hasta tocar el banco suavemente, sin desplomarte, y vuelve a subir. Ajusta la altura o recorrido si molestan el pie o la cadera.'},
  'homeB-hinge':{photo:null,guide:'De pie con mancuernas ligeras a los lados, dobla ligeramente las rodillas y lleva la cadera hacia atrás. Mantén espalda y muñecas rectas, nota tensión suave detrás de las piernas y vuelve a subir apretando glúteos.'},
  'homeB-press':{photo:0,guide:'Ajusta el respaldo del banco a 30–45°. Apoya espalda y pies, sujeta las mancuernas junto al pecho con las palmas enfrentadas y muñecas rectas. Empuja arriba y algo hacia dentro; baja despacio hasta un recorrido cómodo.'},
  'homeB-hip':{photo:null,guide:'Siéntate en una silla firme con pies apoyados y rodillas al ancho de caderas. Coloca un cinturón o banda firme alrededor de los muslos, justo encima de las rodillas. Empuja ambas rodillas hacia fuera de forma gradual sin separarlas; mantén la tensión y relaja despacio.'},
  'homeB-deadbug':{photo:4,guide:'Túmbate boca arriba con brazos hacia el techo y rodillas sobre las caderas. Extiende a la vez un brazo y la pierna contraria sin despegar la zona lumbar del suelo; vuelve y cambia de lado.'}
};
function homeSchedule(date=new Date()){const monday=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()-((date.getDay()+6)%7));const alternate=Math.floor((monday-Date.UTC(2026,8,21))/604800000)%2!==0;return (alternate?['homeB','homeA','homeB']:['homeA','homeB','homeA']).map((id,i)=>({id,day:['Lunes','Miércoles','Viernes'][i],number:i+1}))}
const PROFILE_EXTRAS={age:'',sex:'',healthConditions:'',medications:'',allergies:'',foodPreferences:'',mealSchedule:'',trainingPlace:'',homeEquipment:'',gymEquipment:'',trainingDays:'',sessionMinutes:'',strengthExperience:'',runningStatus:'',runningDays:'',weeklyKm:'',longestRunKm:'',raceName:'',raceDistance:'',raceDate:'',raceGoal:'',raceNotes:''};
function withExtras(obj){const workouts=(Array.isArray(obj.workouts)?obj.workouts:[]).map(w=>({...w,exercises:w.exercises.map(e=>{if(e.id==='homeA-press'&&e.name==='Press con mancuernas en el suelo')return {...e,name:'Press de pecho con mancuernas en banco',note:'8–12 repeticiones · banco plano a 180°, palmas enfrentadas y muñeca recta. Primera semana: 2 series.'};if(e.id==='homeB-shoulder'&&e.name==='Press de hombros sentado')return {...e,name:'Press de hombros en banco',note:'8–12 repeticiones · respaldo a 90° y mancuernas con agarre neutro. Primera semana: 2 series.'};return e})}));const templates=homeWorkouts().filter(w=>!workouts.some(existing=>existing.id===w.id));const filled=workouts.some(w=>w.exercises.length);return {...obj,profile:{...PROFILE_EXTRAS,...obj.profile},workouts:filled?[...workouts,...templates]:[...workouts.filter(w=>w.exercises.length),...templates],runs:Array.isArray(obj.runs)?obj.runs:[],wearableDays:obj.wearableDays&&typeof obj.wearableDays==='object'&&!Array.isArray(obj.wearableDays)?obj.wearableDays:{},mealNotes:obj.mealNotes&&typeof obj.mealNotes==='object'&&!Array.isArray(obj.mealNotes)?obj.mealNotes:{},workoutNotes:obj.workoutNotes&&typeof obj.workoutNotes==='object'&&!Array.isArray(obj.workoutNotes)?obj.workoutNotes:{},aiNotes:Array.isArray(obj.aiNotes)?obj.aiNotes:[]}}
function load(){try{const obj=JSON.parse(localStorage.getItem(STORE));if(valid(obj))return withExtras(obj)}catch{}return withExtras(starter())}
function validMeal(m){return !!(m&&typeof m.id==='string'&&typeof m.name==='string'&&typeof m.amount==='string'&&(!('optional'in m)||typeof m.optional==='boolean')&&(!('day'in m)||(Number.isInteger(m.day)&&m.day>=0&&m.day<=6)))}
function validMealPlan(obj){return !!(obj&&obj.schema==='viveplus.meals.v1'&&Array.isArray(obj.meals)&&obj.meals.length>0&&obj.meals.every(validMeal))}
function valid(obj){const notesOkay=key=>!(key in obj)||(obj[key]&&typeof obj[key]==='object'&&!Array.isArray(obj[key])&&Object.values(obj[key]).every(value=>typeof value==='string'));return !!(obj&&obj.schema==='viva.health.v1'&&obj.profile&&typeof obj.profile==='object'&&typeof obj.profile.name==='string'&&Array.isArray(obj.meals)&&obj.meals.every(validMeal)&&Array.isArray(obj.workouts)&&obj.workouts.every(w=>w&&typeof w.name==='string'&&Array.isArray(w.exercises)&&w.exercises.every(e=>e&&typeof e.id==='string'&&typeof e.name==='string'&&Array.isArray(e.sets)&&e.sets.every(s=>s&&Number.isFinite(Number(s.kg))&&Number.isFinite(Number(s.reps)))))&&Array.isArray(obj.logs)&&obj.logs.every(l=>l&&typeof l.date==='string'&&typeof l.workoutName==='string'&&Array.isArray(l.exercises))&&Array.isArray(obj.metrics)&&obj.metrics.every(m=>m&&typeof m.date==='string')&&(!('runs'in obj)||(Array.isArray(obj.runs)&&obj.runs.every(r=>r&&typeof r.date==='string'&&Number.isFinite(Number(r.distance))&&Number.isFinite(Number(r.minutes)))))&&obj.mealChecks&&typeof obj.mealChecks==='object'&&!Array.isArray(obj.mealChecks)&&notesOkay('mealNotes')&&notesOkay('workoutNotes')&&(!('aiNotes'in obj)||(Array.isArray(obj.aiNotes)&&obj.aiNotes.every(n=>n&&typeof n.id==='string'&&typeof n.date==='string'&&typeof n.text==='string'&&(!('done'in n)||typeof n.done==='boolean')))))}
const WEEK_DAYS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const weekdayIndex=(date=new Date())=>(date.getDay()+6)%7;
function mealDate(index){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-weekdayIndex(date)+index);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
const mealsForDay=index=>data.meals.filter(meal=>meal.day==null||meal.day===index);
let data=load(),view='hoy',workoutIndex=0,homeSlotIndex=0,mealDayIndex=weekdayIndex(),toastTimer,coach=null,coachTick=null;
function save(){data.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(data));render();autoSaveToDrive()}
function toast(message){const box=document.querySelector('#toast');box.textContent=message;box.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('show'),3000)}
function updateStatusText(message){if(/^Vive\+ ya .* actualizado$/.test(message))return 'Vive+ ya está actualizado';const normalized=String(message).toLowerCase();if(normalized.includes('disponible')&&normalized.includes('verde'))return 'Actualización disponible: pulsa el botón verde de arriba';return message}
function heading(kicker,title,detail=''){return `<div class="page-head"><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1>${detail?`<p class="muted">${esc(detail)}</p>`:''}</div>`}
function mealLines(amount){return String(amount||'').split(/\s*·\s*|\r?\n/).map(x=>x.trim()).filter(Boolean)}
function ingredientParts(line){const match=line.match(/^(\d+(?:[.,]\d+)?(?:\s*[–-]\s*\d+(?:[.,]\d+)?)?\s*(?:g|kg|ml|l|ud|unidades?)?)\s+(?:de\s+)?(.+)$/i);return match?{quantity:match[1],food:match[2]}:{quantity:'',food:line}}
function noteKey(date,id){return `${date}:${id}`}
function noteEditor(kind,id,date,label,placeholder){const notes=kind==='meal'?data.mealNotes:data.workoutNotes;return `<div class="daily-note"><label for="note-${esc(kind)}-${esc(id)}-${esc(date)}">${esc(label)}</label><textarea id="note-${esc(kind)}-${esc(id)}-${esc(date)}" data-note-text="${esc(kind)}" data-note-id="${esc(id)}" data-note-date="${esc(date)}" placeholder="${esc(placeholder)}">${esc(notes[noteKey(date,id)]||'')}</textarea><button class="btn dark" data-save-note="${esc(kind)}" data-note-id="${esc(id)}" data-note-date="${esc(date)}">Guardar en Google Drive</button></div>`}
function mealCard(m,check=false,date=today()){const done=!!data.mealChecks[`${date}:${m.id}`];return `<article class="card meal-card"><div class="meal-head"><div class="art ${esc(m.tone||'mint')}">${esc(m.icon||'🍽️')}</div><div class="meal-title"><span class="tag">${esc(m.type)}</span>${m.optional?'<span class="tag optional">Opcional</span>':''}<h3>${esc(m.name)}</h3></div>${check?`<input class="check" aria-label="Marcar ${esc(m.name)} como completada" type="checkbox" data-check-meal="${esc(m.id)}" ${done?'checked':''}>`:`<button class="text-btn" data-edit-meal="${esc(m.id)}" aria-label="Editar ${esc(m.name)}">Editar</button>`}</div><ul class="ingredient-list">${mealLines(m.amount).map(line=>{const item=ingredientParts(line);return `<li>${item.quantity?`<strong>${esc(item.quantity)}</strong>`:''}<span>${esc(item.food)}</span></li>`}).join('')}</ul>${m.notes?`<p class="meal-note">${esc(m.notes)}</p>`:''}${noteEditor('meal',m.id,date,`Lo que comí el ${WEEK_DAYS[weekdayIndex(new Date(`${date}T12:00:00`))].toLowerCase()}`,'Ej.: cambié el salmón por pollo, añadí aceite o quité tomate')}</article>`}
function aiNotesPanel(){const notes=data.aiNotes.filter(n=>!n.done).sort((a,b)=>b.date.localeCompare(a.date));return `<section class="card ai-inbox"><div class="ai-inbox-head"><div><span class="eyebrow">TU ESPACIO CON LA IA</span><h2>Notas para la IA</h2></div><span class="pill">${notes.length} pendientes</span></div><p>Cuéntame qué hiciste o qué quieres que prepare para ti en la app. Lo guardaré para retomarlo en el chat.</p><button class="btn dark wide" data-add-ai-note>＋ Escribir una nota</button>${notes.length?`<div class="ai-note-list">${notes.slice(0,3).map(n=>`<article class="ai-note"><div class="ai-note-meta"><time>${esc(fmtDate(n.date))}</time><span class="tag">Pendiente</span></div><p>${esc(n.text)}</p><button class="text-btn" data-complete-ai-note="${esc(n.id)}">Marcar atendida</button></article>`).join('')}</div>`:'<p class="ai-empty">No tienes notas pendientes. Las atendidas se conservan en Perfil.</p>'}</section>`}
function aiNotesHistoryPanel(){const notes=data.aiNotes.filter(n=>n.done).sort((a,b)=>b.date.localeCompare(a.date));if(!notes.length)return '';return `<section class="card ai-history"><details><summary>Notas atendidas (${notes.length})</summary><div class="ai-note-list">${notes.map(n=>`<article class="ai-note"><div class="ai-note-meta"><time>${esc(fmtDate(n.date))}</time><span class="tag ai-done">Atendida</span></div><p>${esc(n.text)}</p></article>`).join('')}</div></details></section>`}
function nextWorkout(){const slots=homeSchedule();const day=(new Date().getDay()+6)%7;const slot=day<=0?0:day<=2?1:2;const index=data.workouts.findIndex(w=>w.id===slots[slot].id);return index>=0?index:0}
function homeWorkoutSubtitle(workout){if(['homeA','homeB'].includes(workout?.id)&&workout.subtitle?.includes('25–30'))return 'Fuerza en casa · objetivo 40 min';return workout?.subtitle||'Prepara tu entrenamiento'}
workoutIndex=nextWorkout();
const homeNumber=value=>Number(value).toLocaleString('es-ES');
const homeDate=date=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(new Date(`${date}T12:00:00`));
function homeDays(){return Object.values(data.wearableDays||{}).filter(day=>day&&/^\d{4}-\d{2}-\d{2}$/.test(day.date)).sort((a,b)=>b.date.localeCompare(a.date))}
function homeWearableWorkouts(){return Object.values(data.wearableWorkouts||{}).filter(w=>w&&typeof w.date==='string').sort((a,b)=>b.start.localeCompare(a.start))}
function homeWorkoutName(name){return ({'Exterior Ejecutar':'Carrera al aire libre','Deportes de Surf':'Deportes de surf'})[name]||name}
function homeMetric(icon,label,value,unit,detail,tone){return `<article class="home-metric ${tone}"><span class="home-metric-icon" aria-hidden="true">${icon}</span><span class="home-metric-label">${esc(label)}</span><strong>${value==null?'—':esc(homeNumber(value))}${value==null?'':`<small>${esc(unit)}</small>`}</strong><span class="home-metric-detail">${esc(detail)}</span></article>`}
function homeBars(days,key,title,unit){const ordered=[...days].reverse().slice(-7),values=ordered.map(day=>Number(day[key])||0),top=Math.max(1,...values);return `<div class="home-trend"><div class="home-trend-head"><h3>${esc(title)}</h3><span>${esc(unit)}</span></div><div class="home-bars" role="img" aria-label="${esc(ordered.map((day,i)=>`${homeDate(day.date)}: ${values[i]} ${unit}`).join('; '))}">${ordered.map((day,i)=>`<div class="home-bar-col"><div class="home-bar-track"><i style="height:${Math.max(6,Math.round(values[i]/top*100))}%"></i></div><small>${esc(new Intl.DateTimeFormat('es-ES',{weekday:'short'}).format(new Date(`${day.date}T12:00:00`)).replace('.',''))}</small></div>`).join('')}</div></div>`}
function homeHealthPanel(){const days=homeDays();if(!days.length)return `<section class="home-empty card"><span class="home-empty-icon">⌁</span><h2>Tu historia empieza aquí</h2><p>Cuando lleguen los datos del reloj, verás en Inicio tu sueño, pasos, actividad y entrenamientos.</p><button class="btn dark" data-go="progreso">Ver mi progreso</button></section>`;const latest=days[0],week=days.slice(0,7),workouts=homeWearableWorkouts(),first=week.at(-1)?.date,last=latest.date,weekWorkouts=workouts.filter(w=>w.date>=first&&w.date<=last),totalSteps=week.reduce((sum,d)=>sum+(Number(d.steps)||0),0),sleepValues=week.map(d=>Number(d.sleepHours)).filter(n=>Number.isFinite(n)&&n>0),sleepAverage=sleepValues.length?(sleepValues.reduce((a,b)=>a+b,0)/sleepValues.length).toFixed(1).replace('.',','):null,mostRecent=workouts[0];return `<section class="home-hero"><div class="home-hero-top"><span class="home-overline">✳ TU RESUMEN PERSONAL</span><span class="home-hero-date">Hasta el ${esc(homeDate(latest.date))}</span></div><h2>Tu semana, en movimiento.</h2><p>Cada dato cuenta una parte de lo que has hecho. Aquí puedes verlo con calma y seguir tu progreso.</p><div class="home-hero-stats"><div><strong>${esc(weekWorkouts.length)}</strong><span>entrenamientos<br>del reloj</span></div><div><strong>${esc(homeNumber(totalSteps))}</strong><span>pasos en los ${week.length}<br>días recibidos</span></div></div></section>
<div class="section-title home-section-title"><div><span class="eyebrow">ÚLTIMO DÍA EXPORTADO</span><h2>${esc(homeDate(latest.date))}</h2></div><button class="text-btn" data-go="progreso">Ver detalle →</button></div><div class="home-metric-grid">${homeMetric('↗','Pasos',latest.steps,'pasos','Movimiento del día','tone-lime')}${homeMetric('☾','Sueño',latest.sleepHours,'h','Tiempo dormido','tone-lilac')}${homeMetric('✳','Kcal activas',latest.activeKcal,'kcal',latest.activeKcal==null?'Pendiente de exportar':'Actividad de todo el día','tone-peach')}${homeMetric('♥','Pulso en reposo',latest.restingBpm,'ppm','Lectura de Apple Salud','tone-rose')}</div>
<div class="section-title home-section-title"><div><span class="eyebrow">TU EVOLUCIÓN</span><h2>Los últimos días</h2></div></div><div class="card home-trends">${homeBars(week,'steps','Pasos','pasos')}${homeBars(week,'sleepHours','Sueño','horas')}<p>El sueño medio de los días recibidos es <strong>${sleepAverage==null?'—':`${esc(sleepAverage)} h`}</strong>. Observa la tendencia a tu ritmo.</p></div>
<div class="section-title home-section-title"><div><span class="eyebrow">MOVIMIENTO</span><h2>Actividad reciente</h2></div><button class="text-btn" data-go="progreso">Historial →</button></div>${mostRecent?`<article class="home-last-workout card"><div class="home-workout-mark" aria-hidden="true">↗</div><div class="home-workout-body"><span class="home-card-kicker">ÚLTIMO ENTRENAMIENTO · ${esc(homeDate(mostRecent.date))}</span><h3>${esc(mostRecent.displayName||homeWorkoutName(mostRecent.name))}</h3><div class="home-workout-facts"><span>${esc(mostRecent.minutes??'—')} min</span>${mostRecent.activeKcal==null?'':`<span>${esc(homeNumber(mostRecent.activeKcal))} kcal activas</span>`}${mostRecent.averageBpm==null?'':`<span>Pulso medio ${esc(mostRecent.averageBpm)} ppm</span>`}</div></div></article>`:'<div class="home-empty card"><p>Cuando registres un entrenamiento con el reloj, aparecerá aquí.</p></div>'}<p class="home-data-note">Las kcal de un entrenamiento ya forman parte de la actividad del día; no se suman dos veces. Datos importados de Apple Salud.</p>`}
function todayView(){const todayMeals=mealsForDay(weekdayIndex());const required=todayMeals.filter(m=>!m.optional);const done=required.filter(m=>data.mealChecks[`${today()}:${m.id}`]).length;const w=data.workouts[nextWorkout()]||data.workouts[0];return `${heading(new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date()),`Hola, ${data.profile.name||'bienvenido'} 👋`,'Tu espacio para cuidarte, paso a paso.')}
${homeHealthPanel()}${aiNotesPanel()}
<div class="section-title"><h2>Comidas de hoy</h2><button class="text-btn" data-go="comidas">Ver semana →</button></div><p class="home-meal-progress">${done} de ${required.length} comidas marcadas hoy</p>${todayMeals.map(m=>mealCard(m,true)).join('')||'<div class="empty">No hay comidas para hoy.</div>'}
<div class="section-title"><h2>Próximo entrenamiento</h2><button class="text-btn" data-go="entrenar">Abrir →</button></div><div class="banner"><div class="art">🏋️</div><div><h3>${esc(w?.name||'Tu sesión')}</h3><p>${esc(homeWorkoutSubtitle(w))}</p></div></div>
<p class="hint">Los ejemplos iniciales proceden de tu historial. Comprueba que encajan con tus indicaciones actuales antes de seguirlos.</p>`}
function mealsView(){const date=mealDate(mealDayIndex);return `${heading('Nutrición','Tu semana de comidas','Menú de siete días para tu fase baja en FODMAP, con notas para contarme cada cambio.')}
<div class="banner"><div class="art">🥗</div><div><h3>Tu plan, a tu manera</h3><p>Puedes cambiar alimentos, cantidades y notas cuando lo necesites.</p></div></div>
<div class="meal-week" role="group" aria-label="Días de la semana">${WEEK_DAYS.map((day,i)=>`<button class="chip ${i===mealDayIndex?'active':''}" data-meal-day="${i}" aria-pressed="${i===mealDayIndex}">${day.slice(0,3)}</button>`).join('')}</div>
<div class="section-title"><h2>${WEEK_DAYS[mealDayIndex]} ${fmtDate(date)}</h2><button class="text-btn" data-add-meal>+ Añadir</button></div>${mealsForDay(mealDayIndex).map(m=>mealCard(m,false,date)).join('')||'<div class="empty"><span class="emoji">🍽️</span>No hay comidas para este día.</div>'}
<p class="hint">La pauta baja en FODMAP es temporal. Revisa las raciones y los cambios de fase con tu profesional. Marca lo realizado desde Hoy y deja aquí tus sustituciones.</p>`}
function exerciseCard(e,wi){const info=HOME_EXERCISE_DETAILS[e.id];const photo=info&&Number.isInteger(info.photo)?`<span class="exercise-photo" role="img" aria-label="Foto ilustrativa de ${esc(e.name)}" style="--photo-x:${(info.photo%3)*50}%;--photo-y:${Math.floor(info.photo/3)*50}%"></span>`:`<div class="art lavender">${esc(e.icon||'🏋️')}</div>`;return `<div class="exercise"><div class="row">${photo}<div><h3>${esc(e.name)}</h3><p>${esc(e.note||'')}</p></div><button class="text-btn" data-edit-exercise="${esc(e.id)}" data-wi="${wi}">Editar</button></div>${info?`<p class="exercise-guide"><strong>Cómo se hace:</strong> ${esc(info.guide)}</p>`:''}<div class="set-table set-head"><span>Serie</span><span>Peso (kg)</span><span>Reps</span><span></span></div>${e.sets.map((s,si)=>`<div class="set-table"><strong>${si+1}</strong><input aria-label="Peso serie ${si+1} de ${esc(e.name)}" type="number" min="0" step="0.5" inputmode="decimal" value="${Number(s.kg)||0}" data-set="${esc(e.id)}" data-wi="${wi}" data-si="${si}" data-field="kg"><input aria-label="Repeticiones serie ${si+1} de ${esc(e.name)}" type="number" min="0" step="1" inputmode="numeric" value="${Number(s.reps)||0}" data-set="${esc(e.id)}" data-wi="${wi}" data-si="${si}" data-field="reps"><span>×</span></div>`).join('')}</div>`}
function weekSlotDate(index){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7)+index*2);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function coachStep(w){const steps=[];for(let ei=0;ei<w.exercises.length;ei++)for(let si=0;si<w.exercises[ei].sets.length;si++)steps.push({ei,si});return steps}
function coachSpeak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const msg=new SpeechSynthesisUtterance(text);msg.lang='es-ES';msg.rate=.92;window.speechSynthesis.speak(msg)}
function coachCurrent(w){const steps=coachStep(w),step=steps[coach?.stepIndex||0];return step?{...step,exercise:w.exercises[step.ei],total:steps.length}:null}
function coachPanel(w){const c=coachCurrent(w),rest=coach?.phase==='rest',complete=coach?.phase==='done';const display=rest?coach.remaining:coach?.phase==='warmup'?coach.remaining:0;const label=complete?'Rutina completada':rest?'Descanso':coach?.phase==='warmup'?'Calentamiento':c?`Ejercicio ${c.ei+1} de ${w.exercises.length} · serie ${c.si+1} de ${c.exercise.sets.length}`:'Rutina';const description=complete?'¡Buen trabajo! Estira suavemente y guarda la sesión.':rest?'Toma agua y prepárate para la siguiente serie.':coach?.phase==='warmup'?'Calienta a tu ritmo durante 5 minutos.':c?`${esc(c.exercise.name)} · ${esc(c.exercise.sets[c.si].reps)} repeticiones`:'Sigue la indicación por voz.';return `<section class="card coach-card" aria-live="polite"><div class="coach-label">${label}</div><h2>${description}</h2><div class="coach-clock" data-coach-clock>${display?coachTime(display):'—:—'}</div>${rest||coach?.phase==='warmup'?`<div class="coach-progress"><i data-coach-progress style="width:${Math.max(0,Math.min(100,(display/(coach?.phase==='warmup'?300:90))*100))}%"></i></div>`:''}<div class="btn-row">${coach?.phase==='warmup'?`<button class="btn dark" data-coach-begin ${coach.paused?'':'hidden'}>Empezar primera serie</button>`:rest?`<button class="btn dark" data-coach-skip>Terminé el descanso</button>`:complete?`<button class="btn dark" data-coach-stop>Finalizar</button>`:`<button class="btn dark" data-coach-set>✓ Serie terminada</button>`}${!complete?`<button class="btn ghost" data-coach-pause>${coach.paused?'Continuar':'Pausar'}</button><button class="btn ghost" data-coach-stop>Parar</button>`:''}</div></section>`}
function coachTime(seconds){const n=Math.max(0,seconds|0);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function coachRender(){if(view!=='entrenar')return;const node=document.querySelector('.coach-card');if(!node)return;const w=data.workouts.find(x=>x.id===coach?.workoutId);if(w&&w.id===data.workouts[workoutIndex]?.id){node.outerHTML=coachPanel(w);if(coach?.phase==='rest'||coach?.phase==='warmup'){const fill=document.querySelector('[data-coach-progress]');if(fill)fill.style.width=`${Math.max(0,Math.min(100,coach.remaining/(coach.phase==='warmup'?300:90)*100))}%`}}}
function coachStart(id){const w=data.workouts.find(x=>x.id===id);if(!w)return;clearInterval(coachTick);coach={workoutId:id,phase:'warmup',stepIndex:0,remaining:300,paused:false};coachSpeak(`Rutina de ${w.name}. Empezamos con cinco minutos de calentamiento suave. Después te indicaré cada ejercicio y las repeticiones.`);coachTick=setInterval(()=>{if(!coach||coach.paused)return;if(coach.remaining>0)coach.remaining--;if(coach.remaining===0){if(coach.phase==='warmup'){coach.paused=true;coachSpeak('Calentamiento terminado. Pulsa empezar primera serie cuando estés listo.')}else coachAdvance();}coachRender()},1000);render()}
function coachAnnounce(){const w=data.workouts.find(x=>x.id===coach?.workoutId),c=w&&coachCurrent(w);if(c)coachSpeak(`${c.exercise.name}. Serie ${c.si+1} de ${c.exercise.sets.length}, ${c.exercise.sets[c.si].reps} repeticiones. Cuando termines, pulsa serie terminada.`)}
function coachAdvance(){const w=data.workouts.find(x=>x.id===coach?.workoutId);if(!w)return;coach.stepIndex++;if(coach.stepIndex>=coachStep(w).length){coach.phase='done';coach.paused=true;clearInterval(coachTick);coachSpeak('Has terminado la rutina. Enhorabuena. Tómate unos minutos para volver a la calma.');return}coach.phase='set';coach.remaining=0;coach.paused=false;coachAnnounce()}
function coachPause(){if(!coach)return;coach.paused=!coach.paused;if(!coach.paused&&coach.phase==='warmup'&&coach.remaining===0){coach.phase='set';coachSpeak('Empieza tu primera serie cuando estés listo.')}else if(!coach.paused&&coach.phase==='rest'&&coach.remaining===0)coachAdvance();coachRender()}
function coachSetDone(){if(!coach)return;const w=data.workouts.find(x=>x.id===coach.workoutId);if(w&&coach.stepIndex===coachStep(w).length-1){coachAdvance();coachRender();return}coach.phase='rest';coach.remaining=90;coach.paused=false;coachSpeak('Serie terminada. Descansa un minuto y medio.');coachRender()}
function coachSkip(){if(!coach)return;if(coach.phase==='warmup'){coach.phase='set';coach.paused=false;coachSpeak('Calentamiento terminado. Empieza tu primera serie cuando estés listo.')}else if(coach.phase==='rest'){coach.remaining=0;coachAdvance()}coachRender()}
function coachStop(){clearInterval(coachTick);coachTick=null;if('speechSynthesis'in window)window.speechSynthesis.cancel();coach=null;render()}
function trainingView(){const slots=homeSchedule();const slot=slots[homeSlotIndex]||slots[0];workoutIndex=data.workouts.findIndex(w=>w.id===slot.id);const w=data.workouts[workoutIndex];return `${heading('Movimiento','Entrena con criterio','Tres días por semana · lunes, miércoles y viernes · unos 40 min por sesión.')}
<div class="toolbar home-week">${slots.map((item,i)=>`<button class="chip ${i===homeSlotIndex?'active':''}" data-home-slot="${i}" aria-pressed="${i===homeSlotIndex}">${item.day}<small>${esc(item.id==='homeA'?'Casa A':'Casa B')}</small></button>`).join('')}</div>${w?`<div class="hero"><span class="pill">${slot.day} · sesión ${slot.number} de 3</span><h2>${esc(w.name)}</h2><p>Objetivo: 40 minutos · ${w.exercises.length} ejercicios guiados</p></div><div class="notice">Reserva unos 5 min para calentar y 3 min para volver a la calma. Descansa 90 s entre series y prepara el siguiente ejercicio con calma. El cronómetro te guía los descansos; tú marcas cuándo acabas cada serie para adaptarlo a tu ritmo. Usa un peso cómodo y detén cualquier ejercicio que aumente el dolor del pie o la muñeca.</div>${coach?.workoutId===w.id?coachPanel(w):`<button class="btn dark wide coach-start" data-coach-start="${esc(w.id)}">▶ Iniciar rutina guiada</button>`}<div class="section-title"><h2>Ejercicios</h2><button class="text-btn" data-add-exercise>+ Añadir</button></div><div class="exercise-list">${w.exercises.map(e=>exerciseCard(e,workoutIndex)).join('')}</div><div class="notice">Las fotos son orientativas. Si un ejercicio aumenta el dolor del pie o de la muñeca, deténlo y anótalo al guardar la sesión.</div><div class="card">${noteEditor('workout',w.id,weekSlotDate(homeSlotIndex),`Mi nota del ${slot.day.toLowerCase()} ${fmtDate(weekSlotDate(homeSlotIndex))}`,'Ej.: cambié un ejercicio, hice menos series o apareció una molestia')}</div><button class="btn dark wide" data-finish>Guardar entrenamiento</button>`:'<div class="empty">No hay entrenamiento en casa para este día.</div>'}`}
function wearablePanel(){const days=Object.values(data.wearableDays||{}).filter(d=>d&&typeof d.date==='string').sort((a,b)=>b.date.localeCompare(a.date));if(!days.length)return '';const latest=days[0];const value=(v,suffix='')=>v==null?'—':`${esc(v)}${suffix}`;return `<div class="section-title"><h2>Apple Watch</h2><span class="pill">Apple Salud</span></div><div class="card"><p class="muted">Datos del ${esc(fmtDate(latest.date))}. Se actualizan cuando el iPhone exporta a Drive y Vive+ recibe la importación.</p><div class="wearable-grid"><div><span>Pasos</span><strong>${value(latest.steps)}</strong></div><div><span>Sueño</span><strong>${value(latest.sleepHours,' h')}</strong></div><div><span>Kcal activas</span><strong>${value(latest.activeKcal)}</strong></div><div><span>Pulso en reposo</span><strong>${value(latest.restingBpm,' ppm')}</strong></div></div>${latest.minimumBpm!=null&&latest.maximumBpm!=null?`<p class="hint">Pulsaciones registradas: ${esc(latest.minimumBpm)}–${esc(latest.maximumBpm)} ppm.</p>`:''}</div><div class="card progress-list">${days.slice(0,7).map(d=>`<div class="progress-row"><span>${esc(fmtDate(d.date))}</span><span>${value(d.steps)} pasos · ${value(d.sleepHours,' h')} sueño</span><span>${value(d.activeKcal,' kcal')}</span></div>`).join('')}</div>`}
function wearableCaloriesPanel(){const days=Object.values(data.wearableDays||{}).filter(d=>d&&typeof d.date==='string').sort((a,b)=>b.date.localeCompare(a.date));if(!days.length||days[0].basalKcal==null)return '';const latest=days[0];return `<div class="card"><h3>Gasto energético del ${esc(fmtDate(latest.date))}</h3><div class="wearable-grid"><div><span>En reposo</span><strong>${esc(latest.basalKcal)} kcal</strong></div><div><span>Total del día</span><strong>${latest.totalKcal==null?'—':`${esc(latest.totalKcal)} kcal`}</strong></div></div><p class="hint">El total suma reposo y actividad. Las kcal de los entrenamientos ya forman parte de la actividad; no se añaden otra vez.</p></div>`}
function wearableWorkoutPanel(){const workouts=Object.values(data.wearableWorkouts||{}).filter(w=>w&&typeof w.start==='string').sort((a,b)=>b.start.localeCompare(a.start));if(!workouts.length)return '';return `<div class="section-title"><h2>Entrenamientos del reloj</h2><span class="pill">${workouts.length} sesiones</span></div><div class="card timeline">${workouts.slice(0,12).map(w=>`<div class="timeline-item"><b>${esc(w.displayName||w.name)} · ${esc(fmtDate(w.date))}</b><p>${w.minutes==null?'':`${esc(w.minutes)} min`}${w.activeKcal==null?'':` · ${esc(w.activeKcal)} kcal activas`}${w.averageBpm==null?'':` · Pulso medio ${esc(w.averageBpm)} ppm`}${w.maximumBpm==null?'':` · Máx. ${esc(w.maximumBpm)} ppm`}</p></div>`).join('')}</div>`}
function progressView(){const sorted=[...data.metrics].sort((a,b)=>b.date.localeCompare(a.date));const last=sorted.find(m=>m.weight!=null||m.waist!=null)||{};const logs=[...data.logs].sort((a,b)=>b.date.localeCompare(a.date));return `${heading('Evolución','Cada paso cuenta','Tus medidas, entrenamientos y sensaciones en un mismo sitio.')}
<div class="grid-2"><div class="stat-card"><span class="mini-label">Peso actual</span><div class="big">${last.weight??'—'} <small>kg</small></div></div><div class="stat-card"><span class="mini-label">Cintura</span><div class="big">${last.waist??'—'} <small>cm</small></div></div></div>
${wearablePanel()}
${wearableCaloriesPanel()}
${wearableWorkoutPanel()}
<div class="section-title"><h2>Medidas</h2><button class="text-btn" data-add-metric>+ Registrar</button></div><div class="card progress-list">${sorted.slice(0,6).map(m=>`<div class="progress-row"><span>${esc(fmtDate(m.date))}</span><span>${m.weight??'—'} kg · ${m.waist??'—'} cm</span><span>${m.footPain==null?'':`Pie ${m.footPain}/10`}</span></div>`).join('')||'<p class="muted">Todavía no hay medidas.</p>'}</div>
<div class="section-title"><h2>Entrenamientos</h2><span class="pill">${logs.length} sesiones</span></div>${logs.length?`<div class="card timeline">${logs.slice(0,12).map(l=>`<div class="timeline-item"><b>${esc(l.workoutName)} · ${esc(fmtDate(l.date))}</b><p>${l.exercises.length} ejercicios${l.notes?` · ${esc(l.notes)}`:''}</p></div>`).join('')}</div>`:'<div class="empty"><span class="emoji">📈</span>Tu progreso aparecerá al guardar la primera sesión.</div>'}
<div class="section-title"><h2>Caminar y correr</h2><button class="text-btn" data-add-run>+ Registrar</button></div>${data.runs.length?`<div class="card timeline">${[...data.runs].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12).map(r=>`<div class="timeline-item"><b>${esc(r.type==='run'?'Carrera':'Caminata')} · ${esc(fmtDate(r.date))}</b><p>${esc(r.distance)} km · ${esc(r.minutes)} min${r.pain!=null?` · Dolor ${esc(r.pain)}/10`:''}${r.notes?` · ${esc(r.notes)}`:''}</p></div>`).join('')}</div>`:'<div class="empty"><span class="emoji">🏃</span>Cuando vuelvas a caminar o correr, registra aquí la distancia, el tiempo y cómo responde el pie.</div>'}`}
function field(label,name,value='',type='text',attrs=''){return `<div class="field"><label for="f-${name}">${esc(label)}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`}
function choice(label,name,value,options){return `<div class="field"><label for="f-${name}">${esc(label)}</label><select id="f-${name}" name="${name}">${options.map(([key,text])=>`<option value="${esc(key)}" ${key===value?'selected':''}>${esc(text)}</option>`).join('')}</select></div>`}
function area(label,name,value,placeholder=''){return `<div class="field"><label for="f-${name}">${esc(label)}</label><textarea id="f-${name}" name="${name}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></div>`}
function profileView(){const p=data.profile;return `${heading('Sobre ti','Tu perfil','Tu contexto ayuda a ajustar la alimentación y el entrenamiento.')}
<div class="card"><div class="section-title" style="margin:0 0 16px"><h2>Datos personales</h2><span class="pill">Privado en este dispositivo</span></div><div class="form-grid">${field('Nombre','name',p.name)}${field('Edad','age',p.age,'number','min="1" max="120"')}${choice('Sexo (opcional)','sex',p.sex,[['','Sin indicar'],['male','Hombre'],['female','Mujer'],['other','Otro']])}${field('Altura (cm)','height',p.height,'number','min="1" step="1"')}${field('Peso inicial (kg)','weight',p.weight,'number','min="1" step="0.1"')}${field('Cintura inicial (cm)','waist',p.waist,'number','min="1" step="0.1"')}${field('Sueño habitual (h)','sleep',p.sleep,'number','min="0" max="24" step="0.5"')}</div>${area('Objetivo principal','goal',p.goal)}${area('Actividad actual','activity',p.activity)}${area('Lesiones y limitaciones','limitations',p.limitations)}${area('Enfermedades o condiciones relevantes','healthConditions',p.healthConditions)}${area('Medicación habitual','medications',p.medications)}${area('Alergias o intolerancias','allergies',p.allergies)}${area('Preferencias alimentarias','foodPreferences',p.foodPreferences)}${area('Horarios de comidas y turnos','mealSchedule',p.mealSchedule)}${area('Dieta y salud digestiva','dietNotes',p.dietNotes)}
<hr class="divider"><div class="section-title"><h2>Dónde entrenas</h2></div>${choice('Lugar habitual','trainingPlace',p.trainingPlace,[['','Seleccionar'],['home','En casa'],['gym','En gimnasio'],['both','En casa y gimnasio']])}${area('Material en casa','homeEquipment',p.homeEquipment,'Ej.: mancuernas ajustables, bandas, barra de dominadas')}${area('Material en el gimnasio','gymEquipment',p.gymEquipment,'Ej.: prensa, poleas, máquinas, pesos libres')}<div class="form-grid">${field('Días disponibles por semana','trainingDays',p.trainingDays,'number','min="0" max="7"')}${field('Minutos por sesión','sessionMinutes',p.sessionMinutes,'number','min="1" step="5"')}</div>${choice('Experiencia de fuerza','strengthExperience',p.strengthExperience,[['','Seleccionar'],['beginner','Principiante'],['intermediate','Intermedia'],['advanced','Avanzada']])}
<hr class="divider"><div class="section-title"><h2>Si preparas una carrera</h2></div>${choice('Situación al correr','runningStatus',p.runningStatus,[['','Seleccionar'],['not_running','Ahora no corro'],['returning','Volviendo a correr'],['regular','Corro habitualmente']])}<div class="form-grid">${field('Días que corres por semana','runningDays',p.runningDays,'number','min="0" max="7"')}${field('Kilómetros semanales','weeklyKm',p.weeklyKm,'number','min="0" step="0.1"')}${field('Tirada más larga reciente (km)','longestRunKm',p.longestRunKm,'number','min="0" step="0.1"')}</div><div class="form-grid">${field('Nombre de la carrera','raceName',p.raceName)}${field('Fecha prevista','raceDate',p.raceDate,'date')}</div><div class="form-grid">${field('Distancia objetivo (km)','raceDistance',p.raceDistance,'number','min="0" step="0.1"')}${field('Objetivo de tiempo','raceGoal',p.raceGoal,'text','placeholder="Ej.: terminar o 2 h"')}</div>${area('Experiencia y restricciones al correr','raceNotes',p.raceNotes,'Ej.: ritmo, dolor, tiempo sin correr')}${area('Otras notas','notes',p.notes)}<button class="btn dark wide" data-save-profile>Guardar perfil</button></div>
<div class="section-title"><h2>Tus datos</h2></div><div class="card"><p class="muted">Exporta tu seguimiento para compartirlo aquí. Importa un archivo completo o un plan de comidas; el plan de comidas conserva tu perfil, rutinas e historial.</p><div class="btn-row"><button class="btn" data-export>Exportar</button><button class="btn ghost" data-import>Importar</button></div><hr class="divider"><p class="profile-note">El archivo contiene información de salud. Compártelo solo con quien elijas. La sincronización con Google Drive se activa solo cuando vinculas un archivo.</p></div>
${aiNotesHistoryPanel()}
<div class="section-title"><h2>Google Drive</h2></div><div class="card"><p class="muted">Elige una vez un archivo en Google Drive. Después, Vive+ guardará tus cambios y cargará los cambios nuevos de Drive al abrir la app.</p>${window.ViveNative?.linkJson?'<div class="btn-row"><button class="btn" data-link-drive>Vincular archivo</button><button class="btn ghost" data-refresh-drive>Actualizar mis datos</button></div><button class="text-btn" data-unlink-drive>Desvincular archivo</button>':'<p class="hint">La vinculación automática está disponible en la APK Android actualizada.</p>'}${syncPaused?'<div class="notice">Hay cambios simultáneos sin combinar. Tus datos locales siguen guardados; pide ayuda en este chat antes de continuar.</div>':''}<p class="hint">Al abrir el selector de Android, elige Drive y una carpeta privada. En el ordenador, Google Drive para escritorio mostrará el archivo sincronizado.</p></div>
<div class="section-title"><h2>Actualizaciones</h2></div><div class="card"><p class="muted">Busca mejoras de Vive+ cuando estén publicadas. Tus registros se mantienen al actualizar.</p>${field('Dirección HTTPS de actualizaciones','updateUrl',localStorage.getItem('vive-update-url')||DEFAULT_UPDATE_URL,'url','placeholder="https://.../release.json"')}<div class="btn-row"><button class="btn ghost" data-save-update-url>Guardar dirección</button><button class="btn dark" data-check-update>Buscar actualización</button></div><p class="hint" style="margin:12px 0 0">La dirección de GitHub Pages ya viene configurada. Solo necesitas internet para buscar actualizaciones.</p></div>`}
function render(){const root=document.querySelector('#view');root.innerHTML=({hoy:todayView,comidas:mealsView,entrenar:trainingView,progreso:progressView,perfil:profileView}[view]||todayView)();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('.avatar').textContent=(data.profile.name||'T')[0].toUpperCase()}
function go(next){view=next;location.hash=next;render();window.scrollTo({top:0,behavior:'smooth'})}
function modal(html,onSubmit){const dlg=document.querySelector('#editor');const content=document.querySelector('#editorContent');content.innerHTML=html;const form=document.querySelector('#editorForm');form.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form).entries());if(onSubmit(values)!==false)dlg.close()};dlg.showModal()}
function aiNoteEditor(){modal(`<h2>Nueva nota para la IA</h2><p class="muted">Puedes contarme qué hiciste, qué necesitas o qué quieres cambiar en Vive+.</p>${field('Fecha','date',today(),'date','required')}<div class="field"><label for="ai-note-text">Tu nota</label><textarea id="ai-note-text" name="text" required placeholder="Ej.: hoy cambié la comida por pollo. También quiero que la app me prepare una cena rápida para mañana."></textarea></div><div class="btn-row"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn dark">Guardar en Google Drive</button></div>`,v=>{const text=v.text.trim();if(!text){toast('Escribe una nota antes de guardar');return false}data.aiNotes.push({id:uid(),date:v.date,text,done:false});save();confirmDriveNoteSave('Nota para la IA guardada en el archivo vinculado')})}
function completeAiNote(id){const note=data.aiNotes.find(n=>n.id===id);if(!note)return;note.done=true;save();toast('Nota marcada como atendida')}
function mealEditor(id){const m=data.meals.find(x=>x.id===id)||{id:uid(),day:mealDayIndex,type:'Comida',name:'',amount:'',icon:'🍽️',tone:'mint',notes:'',optional:false};const isNew=!id;modal(`<h2>${isNew?'Añadir comida':'Editar comida'}</h2>${choice('Día de la semana','day',String(m.day??mealDayIndex),WEEK_DAYS.map((day,i)=>[String(i),day]))}${field('Momento del día','type',m.type)}${field('Nombre del plato','name',m.name,'text','required')}<div class="field"><label for="m-amount">Cada alimento con su cantidad · uno por línea</label><textarea id="m-amount" name="amount" required placeholder="40 g avena&#10;125 g yogur sin lactosa">${esc(mealLines(m.amount).join('\n'))}</textarea></div><label class="option-row"><input type="checkbox" name="optional" ${m.optional?'checked':''}> Comida opcional (no cuenta en el objetivo diario)</label>${field('Icono o emoji','icon',m.icon)}<div class="field"><label for="m-note">Notas y preparación</label><textarea id="m-note" name="notes">${esc(m.notes)}</textarea></div><div class="btn-row"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn dark">Guardar</button></div>${!isNew?'<button type="button" class="text-btn" data-delete-meal style="margin-top:14px">Eliminar comida</button>':''}`,v=>{const lines=mealLines(v.amount);if(!lines.length){toast('Añade al menos un alimento');return false}Object.assign(m,{day:Number(v.day),type:v.type.trim(),name:v.name.trim(),amount:lines.join('\n'),optional:v.optional==='on',icon:v.icon.trim()||'🍽️',notes:v.notes.trim()});if(isNew)data.meals.push(m);save();toast('Comida guardada')});document.querySelector('[data-delete-meal]')?.addEventListener('click',()=>{if(confirm('¿Eliminar esta comida del plan?')){data.meals=data.meals.filter(x=>x.id!==m.id);document.querySelector('#editor').close();save()}})}
function exerciseEditor(id,wi){const w=data.workouts[wi],e=w.exercises.find(x=>x.id===id)||{id:uid(),name:'',icon:'🏋️',sets:[{kg:0,reps:8}],note:''};const isNew=!id;modal(`<h2>${isNew?'Añadir ejercicio':'Editar ejercicio'}</h2>${field('Ejercicio','name',e.name,'text','required')}${field('Icono','icon',e.icon)}${field('Número de series','count',e.sets.length,'number','min="1" max="12" required')}<div class="field"><label for="e-note">Indicaciones</label><textarea id="e-note" name="note">${esc(e.note)}</textarea></div><div class="btn-row"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn dark">Guardar</button></div>${!isNew?'<button type="button" class="text-btn" data-delete-exercise style="margin-top:14px">Eliminar ejercicio</button>':''}`,v=>{const n=Math.max(1,Math.min(12,Number(v.count)||1));e.name=v.name.trim();e.icon=v.icon.trim()||'🏋️';e.note=v.note.trim();while(e.sets.length<n)e.sets.push({kg:0,reps:8});e.sets.length=n;if(isNew)w.exercises.push(e);save();toast('Ejercicio guardado')});document.querySelector('[data-delete-exercise]')?.addEventListener('click',()=>{if(confirm('¿Eliminar este ejercicio del plan?')){w.exercises=w.exercises.filter(x=>x.id!==e.id);document.querySelector('#editor').close();save()}})}
function metricEditor(){modal(`<h2>Registrar medidas</h2>${field('Fecha','date',today(),'date','required')}${field('Peso (kg)','weight','','number','min="1" step="0.1"')}${field('Cintura (cm)','waist','','number','min="1" step="0.1"')}${field('Horas de sueño','sleep','','number','min="0" max="24" step="0.5"')}${field('Dolor de pie (0–10)','footPain','','number','min="0" max="10" step="1"')}${field('Síntomas digestivos (0–10)','digestive','','number','min="0" max="10" step="1"')}<div class="btn-row"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn dark">Guardar</button></div>`,v=>{if(!v.weight&&!v.waist&&!v.sleep&&!v.footPain&&!v.digestive){toast('Introduce al menos un dato');return false}const numeric=k=>v[k]===''?null:Number(v[k]);data.metrics.push({date:v.date,weight:numeric('weight'),waist:numeric('waist'),sleep:numeric('sleep'),footPain:numeric('footPain'),digestive:numeric('digestive')});save();toast('Medidas registradas')})}
function runEditor(){modal(`<h2>Caminar o correr</h2>${choice('Actividad','type','run',[['run','Carrera'],['walk','Caminata']])}${field('Fecha','date',today(),'date','required')}${field('Distancia (km)','distance','','number','min="0" step="0.01" required')}${field('Tiempo (minutos)','minutes','','number','min="0" step="1" required')}${field('Dolor del pie (0–10)','pain','','number','min="0" max="10" step="1"')}<div class="field"><label for="run-notes">Sensaciones</label><textarea id="run-notes" name="notes" placeholder="Ej.: sin dolor durante; molestias al día siguiente"></textarea></div><div class="btn-row"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn dark">Guardar</button></div>`,v=>{data.runs.push({id:uid(),type:v.type,date:v.date,distance:Number(v.distance),minutes:Number(v.minutes),pain:v.pain===''?null:Number(v.pain),notes:v.notes.trim()});save();toast('Actividad guardada')})}
function finishWorkout(){const w=data.workouts[workoutIndex];const date=weekSlotDate(homeSlotIndex);const note=document.querySelector('[data-note-text="workout"]')?.value||data.workoutNotes[noteKey(date,w.id)]||'';modal(`<h2>Guardar ${esc(w.name)}</h2>${field('Fecha','date',today(),'date','required')}<div class="field"><label for="s-note">Sensaciones o molestias</label><textarea id="s-note" name="notes" placeholder="Ej.: energía buena, pie 2/10, muñeca sin dolor">${esc(note)}</textarea></div><div class="btn-row"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn dark">Guardar sesión</button></div>`,v=>{data.logs.push({id:uid(),date:v.date,workoutId:w.id,workoutName:w.name,notes:v.notes.trim(),exercises:structuredClone(w.exercises)});save();toast('Sesión guardada en tu historial')})}
let driveSaveTimer,syncPaused=!!localStorage.getItem('vive-sync-conflict'),driveReadPending=false,noteSavePending='',noteSaveSuccess='Nota guardada en Google Drive';
function autoSaveToDrive(){if(!window.ViveNative?.saveLinkedJson||syncPaused)return;clearTimeout(driveSaveTimer);driveSaveTimer=setTimeout(()=>{if(syncPaused)return;if(driveReadPending){autoSaveToDrive();return}window.ViveNative.saveLinkedJson(JSON.stringify(data))},1500)}
function confirmDriveNoteSave(successMessage){if(window.ViveNative?.hasLinkedJson?.()&&!syncPaused){noteSavePending=data.updatedAt;noteSaveSuccess=successMessage;toast('Nota guardada aquí. Enviando a Google Drive…')}else toast(syncPaused?'Nota guardada aquí. Hay un conflicto de sincronización.':'Nota guardada aquí. Vincula Drive en Perfil para sincronizarla.')}
function saveDailyNote(button){const kind=button.dataset.saveNote,id=button.dataset.noteId,date=button.dataset.noteDate;const entry=kind==='meal'?data.meals.find(m=>m.id===id):data.workouts.find(w=>w.id===id);if(!entry)return;const value=button.parentElement.querySelector('textarea').value.trim();const notes=kind==='meal'?data.mealNotes:data.workoutNotes;const key=noteKey(date,id);if(value)notes[key]=value;else delete notes[key];save();confirmDriveNoteSave('Nota guardada en el archivo vinculado')}
function exportData(){const json=JSON.stringify(data,null,2),filename=`vive-plus-seguimiento-${today()}.json`;if(window.ViveNative){window.ViveNative.exportJson(json,filename);return}const file=new Blob([json],{type:'application/json'});const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Archivo exportado')}
function mergeHistory(incoming,current){const result=withExtras(incoming);const uniqueById=(older,newer)=>[...new Map([...older,...newer].map(x=>[x.id||JSON.stringify(x),x])).values()];result.logs=uniqueById(result.logs,current.logs);result.runs=uniqueById(result.runs,current.runs);result.metrics=[...new Map([...result.metrics,...current.metrics].map(x=>[JSON.stringify(x),x])).values()];result.mealChecks={...result.mealChecks,...current.mealChecks};result.mealNotes={...result.mealNotes,...current.mealNotes};result.workoutNotes={...result.workoutNotes,...current.workoutNotes};result.aiNotes=uniqueById(result.aiNotes,current.aiNotes);return result}
let driveManualCheck=false;
function refreshFromDrive(manual=false){if(window.ViveNative?.readLinkedJson){driveManualCheck=manual;driveReadPending=true;window.ViveNative.readLinkedJson()}else toast('Instala la APK Android actualizada')}
const sameValue=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const emptyCollection=value=>(Array.isArray(value)&&value.length===0)||(value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===0);
function mergeChanges(base,local,remote,path='',conflicts=[]){
  if(path==='updatedAt')return remote;
  if(sameValue(local,base))return remote;
  if(sameValue(remote,base)||sameValue(local,remote))return local;
  // Older Drive snapshots may lack a collection that a newer app initializes as empty.
  if(base===undefined&&emptyCollection(local))return remote;
  if(base===undefined&&emptyCollection(remote))return local;
  if(base===undefined&&Array.isArray(local)&&Array.isArray(remote))return mergeChanges([],local,remote,path,conflicts);
  if(base===undefined&&local&&remote&&typeof local==='object'&&typeof remote==='object'&&!Array.isArray(local)&&!Array.isArray(remote))return mergeChanges({},local,remote,path,conflicts);
  if(Array.isArray(base)&&Array.isArray(local)&&Array.isArray(remote)){
    if(path==='metrics')return [...new Map([...remote,...local].map(item=>[JSON.stringify(item),item])).values()];
    const items=[...base,...local,...remote];
    if(items.length&&items.every(item=>item&&typeof item==='object'&&typeof item.id==='string')){
      const byId=values=>new Map(values.map(item=>[item.id,item]));
      const b=byId(base),l=byId(local),r=byId(remote);
      const ids=[...new Set([...remote,...local,...base].map(item=>item.id))];
      return ids.map(id=>mergeChanges(b.get(id),l.get(id),r.get(id),`${path}[${id}]`,conflicts)).filter(item=>item!==undefined);
    }
    return Array.from({length:Math.max(base.length,local.length,remote.length)},(_,i)=>mergeChanges(base[i],local[i],remote[i],`${path}[${i}]`,conflicts)).filter(item=>item!==undefined);
  }
  if(base&&local&&remote&&typeof base==='object'&&typeof local==='object'&&typeof remote==='object'){
    const out={};for(const key of new Set([...Object.keys(base),...Object.keys(local),...Object.keys(remote)])){const value=mergeChanges(base[key],local[key],remote[key],path?`${path}.${key}`:key,conflicts);if(value!==undefined)out[key]=value}return out;
  }
  conflicts.push(path);return local;
}
window.viveLinkedSaved=text=>{try{const saved=JSON.parse(text);if(valid(saved)){localStorage.setItem('vive-sync-base',JSON.stringify(saved));if(noteSavePending&&saved.updatedAt===noteSavePending){noteSavePending='';toast(noteSaveSuccess)}}}catch{}};
window.viveLinkedReadError=()=>{driveReadPending=false;driveManualCheck=false};
window.viveImportLinkedData=text=>{driveReadPending=false;try{
  const remote=JSON.parse(text);if(!valid(remote))throw Error('Formato de Drive no válido');
  const baseText=localStorage.getItem('vive-sync-base');let merged,conflicts=[];
  if(baseText){const base=JSON.parse(baseText);merged=mergeChanges(base,data,remote,'',conflicts)}
  else if(sameValue(data,remote)){merged=remote}
  else if(Date.parse(data.updatedAt)>Date.parse(remote.updatedAt)){merged=data}
  else if(Date.parse(remote.updatedAt)>Date.parse(data.updatedAt)){for(const field of ['mealNotes','workoutNotes'])for(const [key,value] of Object.entries(data[field]||{}))if(Object.hasOwn(remote[field]||{},key)&&remote[field][key]!==value)conflicts.push(`${field}.${key}`);if(!conflicts.length)merged=mergeHistory(remote,data)}
  else conflicts=['versión inicial'];
  if(conflicts.length){syncPaused=true;localStorage.setItem('vive-sync-conflict',conflicts.join(', '));driveManualCheck=false;toast('Hay cambios simultáneos. Pídeme ayuda por este chat.');return}
  syncPaused=false;localStorage.removeItem('vive-sync-conflict');localStorage.setItem('vive-sync-base',JSON.stringify(remote));
  const changed=!sameValue(data,merged),needsUpload=!sameValue(remote,merged);
  data=merged;if(needsUpload)data.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(data));if(changed)render();
  if(needsUpload)autoSaveToDrive();
  if(changed)toast('Cambios de Drive y de la app combinados');else if(driveManualCheck)toast('Tus datos ya están al día');driveManualCheck=false;
}catch(error){driveManualCheck=false;toast(error.message||'No se pudo leer Drive')}};
function applyBundledMealPlan(){if(!window.ViveNative||Number(localStorage.getItem('vive-meal-plan-version')||0)>=MENU_UPDATE_VERSION)return false;if(data.meals.some(m=>m.id.startsWith('menu6-'))||(data.meals.length===MENU_UPDATE_MEALS.length&&data.meals.every((m,i)=>m.name===MENU_UPDATE_MEALS[i].name))){localStorage.setItem('vive-meal-plan-version',String(MENU_UPDATE_VERSION));return false}data.previousMeals=data.meals;data.meals=structuredClone(MENU_UPDATE_MEALS);data.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(data));localStorage.setItem('vive-meal-plan-version',String(MENU_UPDATE_VERSION));return true}
document.querySelector('#view').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.coachStart)coachStart(b.dataset.coachStart);else if('coachBegin'in b.dataset){coach.phase='set';coach.paused=false;coachAnnounce();coachRender()}else if('coachSet'in b.dataset)coachSetDone();else if('coachPause'in b.dataset)coachPause();else if('coachSkip'in b.dataset)coachSkip();else if('coachStop'in b.dataset)coachStop();else if(b.dataset.go)go(b.dataset.go);else if('addAiNote'in b.dataset)aiNoteEditor();else if(b.dataset.completeAiNote)completeAiNote(b.dataset.completeAiNote);else if('saveNote'in b.dataset)saveDailyNote(b);else if('addMeal'in b.dataset)mealEditor();else if(b.dataset.editMeal)mealEditor(b.dataset.editMeal);else if('mealDay' in b.dataset){mealDayIndex=Number(b.dataset.mealDay);render()}else if('homeSlot' in b.dataset){homeSlotIndex=Number(b.dataset.homeSlot);render()}else if('addExercise'in b.dataset)exerciseEditor(null,workoutIndex);else if(b.dataset.editExercise)exerciseEditor(b.dataset.editExercise,Number(b.dataset.wi));else if('addMetric'in b.dataset)metricEditor();else if('addRun'in b.dataset)runEditor();else if('finish'in b.dataset)finishWorkout();else if('export'in b.dataset)exportData();else if('import'in b.dataset){if(window.ViveNative)window.ViveNative.importJson();else document.querySelector('#importFile').click()}else if('linkDrive'in b.dataset){window.ViveNative?.linkJson(JSON.stringify(data))}else if('refreshDrive'in b.dataset)refreshFromDrive(true);else if('unlinkDrive'in b.dataset){if(confirm('¿Dejar de actualizar el archivo vinculado?'))window.ViveNative?.unlinkJson()}else if('saveUpdateUrl'in b.dataset){const input=document.querySelector('[name="updateUrl"]');const url=input.value.trim();if(url&&!/^https:\/\//i.test(url)){toast('La dirección debe empezar por https://');return}localStorage.setItem('vive-update-url',url);toast('Dirección guardada')}else if('checkUpdate'in b.dataset){checkUpdate(true)}else if('saveProfile'in b.dataset){const root=document.querySelector('#view');for(const key of Object.keys(data.profile)){const input=root.querySelector(`[name="${key}"]`);if(input)data.profile[key]=['age','height','weight','waist','sleep','trainingDays','sessionMinutes','runningDays','weeklyKm','longestRunKm','raceDistance'].includes(key)?(input.value===''?null:Number(input.value)):input.value.trim()}save();toast('Perfil guardado')}});
document.querySelector('#view').addEventListener('change',e=>{const t=e.target;if(t.dataset.checkMeal){data.mealChecks[`${today()}:${t.dataset.checkMeal}`]=t.checked;save()}else if(t.dataset.set){const w=data.workouts[Number(t.dataset.wi)],x=w?.exercises.find(e=>e.id===t.dataset.set),s=x?.sets[Number(t.dataset.si)];if(s){const n=Number(t.value);s[t.dataset.field]=Number.isFinite(n)?Math.max(0,n):0;save();toast('Serie actualizada')}}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
document.querySelector('#profileShortcut').addEventListener('click',()=>go('perfil'));
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['hoy','comidas','entrenar','progreso','perfil'].includes(next)&&next!==view){view=next;render();window.scrollTo(0,0)}});
document.querySelector('#editor').addEventListener('click',e=>{if(e.target===e.currentTarget||e.target.closest('[data-close]'))e.currentTarget.close()});
function importText(text){try{if(text.length>25_000_000)throw Error('El archivo supera 25 MB');const incoming=JSON.parse(text);if(validMealPlan(incoming)){if(!confirm('¿Aplicar este plan de comidas? Sustituirá solo las comidas; tu perfil, rutinas e historial se mantienen.'))return;data.meals=incoming.meals;save();toast('Plan de comidas importado');return}if(!valid(incoming))throw Error('Formato de archivo no compatible');if(!confirm('¿Aplicar este archivo? Se actualizarán el perfil y los planes. Los registros del historial se conservarán.'))return;data=mergeHistory(incoming,data);save();toast('Archivo importado correctamente')}catch(err){toast(err.message||'No se pudo importar el archivo')}}
window.viveImportData=importText;
window.viveUpdateStatus=(message)=>toast(updateStatusText(message));
let updateAvailable=false;
window.viveUpdateAvailability=(available)=>{updateAvailable=!!available;const button=document.querySelector('#updateIndicator');button.classList.toggle('available',updateAvailable);button.setAttribute('aria-label',updateAvailable?'Actualización disponible: instalar':'Comprobar actualizaciones');button.title=updateAvailable?'Instalar actualización de Vive+':'Comprobar actualizaciones'};
function checkUpdate(notify=false){const url=(localStorage.getItem('vive-update-url')||DEFAULT_UPDATE_URL).trim();if(window.ViveNative&&typeof window.ViveNative.checkUpdateAvailability==='function')window.ViveNative.checkUpdateAvailability(url,notify);else if(window.ViveNative&&notify)window.ViveNative.checkForUpdates(url);else if(notify)toast('La actualización OTA estará disponible en la APK')}
function installUpdate(){const url=(localStorage.getItem('vive-update-url')||DEFAULT_UPDATE_URL).trim();if(window.ViveNative)window.ViveNative.checkForUpdates(url);else toast('La actualización OTA estará disponible en la APK')}
document.querySelector('#updateIndicator').addEventListener('click',()=>updateAvailable?installUpdate():checkUpdate(true));
document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkUpdate();refreshFromDrive()}});
document.querySelector('#importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{importText(await file.text())}finally{e.target.value=''}});
const hash=location.hash.slice(1);if(['hoy','comidas','entrenar','progreso','perfil'].includes(hash))view=hash;
if(!window.ViveNative&&'serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
const mealPlanApplied=applyBundledMealPlan();
render();
if(mealPlanApplied)toast('Tu plan de comidas se ha actualizado');
checkUpdate();
if(window.ViveNative?.readLinkedJson)refreshFromDrive();
